# fly.toml app configuration file generated for fly-run-this-function-on-another-machine on 2023-12-17T09:47:59-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fly-run-this-function-on-another-machine"
primary_region = "gru"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
